[variables]
PHP_EXTENSIONS = "pdo_mysql mbstring xml curl zip gd tokenizer fileinfo bcmath ctype"

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction',
  'npm ci'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'bash start.sh'
